#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Jay Taylor (https://github.com/otmof-ops/CigScript)
# SPDX-License-Identifier: Apache-2.0
"""Regenerate docs/ERRORS.md from `cig --json explain` so the reference matches the binary."""
import json, subprocess, sys, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
cig = sys.argv[1] if len(sys.argv) > 1 else str(root / "target/release/cig")
rows = json.loads(subprocess.check_output([cig, "--json", "explain"]))
groups = {
    "1": "Lexing (E1xx)", "2": "Parsing (E2xx)", "3": "Static check (E3xx)", "4": "Types and arity (E4xx)",
    "5": "Runtime (E5xx)", "6": "Raised by the script (E6xx)", "7": "The burn kernel (E7xx)",
    "8": "Command line and environment (E8xx)", "9": "Internal (E9xx)",
}
out = ["# Error codes", "",
       "Every diagnostic `cig` prints carries a stable code, rendered as `error[E502 runtime]: ...`. "
       "`cig explain <code>` prints the entry below at the terminal; `--json` output carries the code in a `code` field. "
       "Generated by `scripts/gen-errors-doc.py`; do not edit by hand.", "",
       "The first digit is the layer that produced the error:", ""]
for k, v in groups.items():
    out.append(f"- {v}")
out.append("")
current = None
for e in rows:
    g = e["code"][1]
    if g != current:
        current = g
        out += ["", f"## {groups[g]}", "", "| code | title | meaning | fix |", "|---|---|---|---|"]
    out.append(f"| `{e['code']}` | {e['title']} | {e['meaning']} | {e['fix']} |")
out.append("")
(root / "docs/ERRORS.md").write_text("\n".join(out))
print("wrote docs/ERRORS.md")
