#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Jay Taylor (https://github.com/otmof-ops/CigScript)
# SPDX-License-Identifier: Apache-2.0
"""Regenerate docs/ERRORS.md and docs/diagnostic.schema.json from the registry.

Both come out of the built binary (`cig --json explain`, `cig explain --schema`),
which reads errors/registry.toml, so the reference, the schema and the binary
can never disagree. tests/registry.rs fails when either file is stale.
"""
import json, subprocess, sys, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
cig = sys.argv[1] if len(sys.argv) > 1 else str(root / "target/release/cig")
nodes = json.loads(subprocess.check_output([cig, "--json", "explain"]))
schema = subprocess.check_output([cig, "explain", "--schema"]).decode()
registry = (root / "errors/registry.toml").read_text()

# Ranges, in order, straight from the registry file (no toml module needed).
ranges = []
cur = None
for line in registry.splitlines():
    s = line.strip()
    if s == "[[range]]":
        cur = {}
        ranges.append(cur)
    elif cur is not None and "=" in s and not s.startswith("#"):
        k, v = s.split("=", 1)
        cur[k.strip()] = v.strip().strip('"')
    elif s.startswith("[[") and s != "[[range]]":
        cur = None

out = [
    "# Error codes",
    "",
    "Every diagnostic `cig` prints carries a stable code, rendered as `error[E502 runtime]: ...`, "
    "and every code is a node in one registry (`errors/registry.toml`): its family, which of the "
    "**four kinds of no** it is ([the lexicon](LEXICON.md#the-four-kinds-of-no)), what it means, "
    "what to type next, and its ranked causes, each with the read-only probe doctor uses to confirm it "
    "and the remedy. `cig explain <code>` prints the same page at the terminal; `cig explain --schema` "
    "prints the JSON Schema that `--json` output follows ([diagnostic.schema.json](diagnostic.schema.json)).",
    "",
    "A code never changes meaning. A retired code is never reused. A code marked *planned* is reserved "
    "for a feature that has not shipped. Generated by `scripts/gen-errors-doc.py`; do not edit by hand.",
    "",
    "## Ranges",
    "",
    "| codes | family | rendered as | meaning |",
    "|---|---|---|---|",
]
for r in ranges:
    out.append(f"| `{r['from']}`–`{r['to']}` | {r['family']} | `{r['kind']}` | {r['meaning']} |")
out += [
    "",
    "## The four kinds of no",
    "",
    "| id | what you hear | whose problem | the manual's name |",
    "|---|---|---|---|",
]
seen_no = {}
for n in nodes:
    seen_no.setdefault(n["no"]["id"], n["no"])
for no in seen_no.values():
    out.append(f"| `{no['id']}` | {no['hear']} | {no['whose']} | {no['manual']} |")

def esc(s: str) -> str:
    return s.replace("|", "\\|")

for r in ranges:
    members = [n for n in nodes if r["from"] <= n["code"] <= r["to"]]
    out += ["", f"## {r['family']} (`{r['from']}`–`{r['to']}`)", "", r["meaning"] + ".", ""]
    if not members:
        out.append("*Reserved; nothing emitted yet.*")
        continue
    out += ["| code | title | kind of no | what to type next |", "|---|---|---|---|"]
    for n in members:
        planned = " *(planned)*" if "planned" in n["tags"] else ""
        out.append(f"| [`{n['code']}`](#{n['code'].lower()}-{n['title'].replace(' ', '-').replace('`','')}) | {esc(n['title'])}{planned} | {n['no']['hear']} | {esc(n['fix'])} |")
    for n in members:
        flags = []
        if "planned" in n["tags"]:
            flags.append("planned")
        if n.get("retired"):
            flags.append("retired")
        meta = f"*{n['kind']} · since {n['since']}"
        if n["arises"]:
            meta += " · arises in " + ", ".join(n["arises"])
        if flags:
            meta += " · " + ", ".join(flags)
        meta += "*"
        out += ["", f"### {n['code']} {n['title']}", "", meta, "",
                f"**Kind of no:** {n['no']['hear']} ({n['no']['whose']}; {n['no']['manual']}).", "",
                n["meaning"], "", f"**What to type next:** {n['fix']}", ""]
        if n["causes"]:
            out.append("**Known causes**, ranked; doctor checks them in this order:")
            out.append("")
            for i, c in enumerate(n["causes"], 1):
                probe = "no probe; a suggestion, not a finding" if c["probe"] == "none" else f"probe `{c['probe']}`"
                extra = []
                if c.get("fixable"):
                    extra.append("doctor can apply it with a y")
                if c.get("needs_burn"):
                    extra.append("needs a burn")
                if not c.get("reversible", True):
                    extra.append("not reversible")
                tail = f" *({'; '.join(extra)})*" if extra else ""
                out.append(f"{i}. {c['why']} ({probe}). **Remedy:** {c['remedy']}{tail}")
            out.append("")
        if n["related"]:
            out.append("Related: " + ", ".join(f"`{x}`" for x in n["related"]) + ".")
            out.append("")
out.append("")
(root / "docs/ERRORS.md").write_text("\n".join(out))
(root / "docs/diagnostic.schema.json").write_text(schema if schema.endswith("\n") else schema + "\n")
print("wrote docs/ERRORS.md and docs/diagnostic.schema.json")
